# HDL-64E
N_SCAN: 64
Horizon_SCAN: 1800
ang_res_x: 0.2
ang_res_y: 0.427
ang_bottom: 24.9
groundScanInd: 50
skip_frame_num: 1     # Check FeatureAssociation::publishCloudsLast()
mapping_process_interval: 0.3     # Check MapOptimization::process()
dataset_name: KITTI
show_point_cloud: false
point_cloud_ratio: 20 # number of points displayed = total points / point_cloud_ratio
