# VLP16
N_SCAN: 16
Horizon_SCAN: 1800
ang_res_x: 0.2
ang_res_y: 2.0
ang_bottom: 15.1
groundScanInd: 7
skip_frame_num: 1
mapping_process_interval: 0.1
dataset_name: nsh_indoor_and_outdoor
show_point_cloud: true
point_cloud_ratio: 20
